### ISSUE TITLE
Black screen / soft lock when exiting a custom level

### ISSUE THREAD

**Issue by IkaRest** [thijnmens/AdofaiCSL#1]
https://user-images.githubusercontent.com/36999341/225112916-530390c7-a488-4696-bf93-5bc5d87639a9.mp4

**Comment by ghost** [comment]
Does not happen in v1.1.0

v2.3.1 (r101) alpha branch (Latest)
UnityModManager v0.25.5.0 (Latest)
AdofaiCSL 1.2.1 (Latest)
AdofaiTweaks v2.6.1 (Latest)
DetailRP 1.0.1 (Latest)
MainBpmChanger 1.0.0 (Latest)
RainingKeys 0.4.1 (Latest)

**Comment by thijnmens** [comment]
I'll look into it 👍
