### ISSUE TITLE
Mod won't open the panel

### ISSUE THREAD

**Issue by PxelBlade** [thijnmens/AdofaiCSL#3]
When I open UMM and click the options button for the mod, it doesn't open the selector. This is the only mod I have that doesn't open that menu. ADOFAI tweaks and rainingkeys both open their panels.

**Comment by thijnmens** [comment]
The mod is currently broken due to a recent game update, although this doesn't sound related with that issue as mine does work. Could you send me your player.log?

**Comment by thijnmens** [comment]
Quick update, i have just released a update for the mod that should've fixed the mod. could you check if the menu opens with this version? (V2.1.0)

**Comment by MaximIce1** [comment]
same issue, update didn't fixed this
![image](https://github.com/thijnmens/AdofaiCSL/assets/79106345/9a3522b7-1b3c-4f08-966c-fd385ebeebbc)

**Comment by thijnmens** [comment]
No it seems to be working fine, do note that since v2.0.0 custom songs are now added to the workshop levels portal instead of appearing in the UMM menu. So could you check if the songs can be found there? They should be all the way at the top. I'll close this issue for now
