### ISSUE TITLE
No mod options

### ISSUE THREAD

**Issue by strayhatpirat** [thijnmens/AdofaiCSL#4]
I followed the instructions, but there is no mod options when I open the game and press Ctrl+F10 : 
![image](https://github.com/thijnmens/AdofaiCSL/assets/16545424/0d2c6a62-d873-4bbb-9c9d-56409b416fa1)

**Comment by thijnmens** [comment]
Seems to be working fine, since version 2.0.0 the songs are being added to your workshop songs in the in-game level selector. They should be all the way at the top when you enter the custom levels portal and go right.
